version: '3'

services:
    db:
        postgres:
            build:
            context: ./postgres
            dockerfile: Dockerfile
            ports:
            - 5432:5432
            volumes:
            - ./postgres/data:/var/lib/postgresql/data
            environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: to_do_list
        networks: 
                - reseau

        adminer:
            build:
            context: ./adminer
            dockerfile: Dockerfile
            ports:
            - 8081:8080
            depends_on:
            - postgres
            networks: 
                    - reseau

            etworks:
                reseau:
                    external: true