version: '3'
services:

  nginx:
        image: nginx:alpine
        volumes:
            - ./php/src:/src
        ports:
            - 8085:80
        restart: on-failure

  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/app
      - ./composer/dependencies:/app/dependencies
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - composer
      - postgres


  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: to_do_list

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - postgres

